### ISSUE TITLE
No support for Ruijie algorithm of version 4?

### ISSUE THREAD

**Issue by cubarco** [DreamAndDead/tinyfox#1]
Hey @DreamAndDead,
    I'm a student of HUST. I'd admire your implementation of EAP process(?). But I have to say that the tinyfox can not become a replacement of the official client of Ruijie(at least presently). Since the EAP part is an all-known part of the entire Ruijie authentication process, and it's the least important part of all. The most important part is the encryption algorithm of Ruijie, which can only be cracked with reverse engineering. And this algorithm has upgraded to version 4. 

P.S. The padding of `MD5-Challenge` and `MD5-Response` is not meaningless, it's exactly the encrypted data.

**Comment by DreamAndDead** [comment]
It's a simple version as I have mentioned in the README, and it can't be a substitute right now. I'm preparing to improve it ;)
 I know little about reverse engineering, Do you have any ideas about the padding part(the encrypted part)?

**Comment by cubarco** [comment]
The encrypted part is the offset `0x12c` to `0x1ab` of MD5-resp packet, which is a 128-byte ASCII string.
I tried to crack the algorithm but could not make it.
Here is some information you may want: [Mentohust issues](https://code.google.com/p/mentohust/issues/list)

**Comment by DreamAndDead** [comment]
Yes you're right, I forgot the encrypted part. I will try to figure it out ;)

**Comment by cubarco** [comment]
Sorry, I made a mistake. The offset of encrypted data is not absolute. It depends on the enviroment, for example, DNS, etc. However, it could be recognized easily.  XD
Good luck, we could discuss about this offline ;)
